package com.krishnajeena.persona.ui.theme
import androidx.compose.ui.graphics.Color

// ============================================
// WARM SUNSET THEME (DEFAULT)
// ============================================
object WarmSunsetLight {
    val primary = Color(0xFFFF6B6B)
    val onPrimary = Color(0xFFFFFFFF)
    val primaryContainer = Color(0xFFFFE5E5)
    val onPrimaryContainer = Color(0xFF8B0000)

    val secondary = Color(0xFF6A1B9A)
    val onSecondary = Color(0xFFFFFFFF)
    val secondaryContainer = Color(0xFFF3E5F5)
    val onSecondaryContainer = Color(0xFF4A148C)

    val tertiary = Color(0xFFFFB300)
    val onTertiary = Color(0xFF000000)
    val tertiaryContainer = Color(0xFFFFECB3)
    val onTertiaryContainer = Color(0xFF7F6000)

    val background = Color(0xFFFFF8F0)
    val onBackground = Color(0xFF1A1A1A)
    val surface = Color(0xFFFFFFFF)
    val onSurface = Color(0xFF1A1A1A)
    val surfaceVariant = Color(0xFFFFF0E6)
    val onSurfaceVariant = Color(0xFF4A4A4A)

    val outline = Color(0xFFE0C4B8)
    val outlineVariant = Color(0xFFF5E6DC)
    val error = Color(0xFFD32F2F)
}

object WarmSunsetDark {
    val primary = Color(0xFFFF8E53)
    val onPrimary = Color(0xFF1A1A1A)
    val primaryContainer = Color(0xFF8B0000)
    val onPrimaryContainer = Color(0xFFFFE5E5)

    val secondary = Color(0xFFBA68C8)
    val onSecondary = Color(0xFF1A1A1A)
    val secondaryContainer = Color(0xFF4A148C)
    val onSecondaryContainer = Color(0xFFF3E5F5)

    val tertiary = Color(0xFFFFD54F)
    val onTertiary = Color(0xFF1A1A1A)
    val tertiaryContainer = Color(0xFF7F6000)
    val onTertiaryContainer = Color(0xFFFFECB3)

    val background = Color(0xFF0D0D0D)
    val onBackground = Color(0xFFFFF8F0)
    val surface = Color(0xFF1C1C1E)
    val onSurface = Color(0xFFFFF8F0)
    val surfaceVariant = Color(0xFF2C2C2E)
    val onSurfaceVariant = Color(0xFFE0D4CC)

    val outline = Color(0xFF3C3C3E)
    val outlineVariant = Color(0xFF2C2C2E)
    val error = Color(0xFFEF5350)
}

// ============================================
// MIDNIGHT PURPLE THEME
// ============================================
object MidnightPurpleLight {
    val primary = Color(0xFF6366F1)
    val onPrimary = Color(0xFFFFFFFF)
    val primaryContainer = Color(0xFFE0E7FF)
    val onPrimaryContainer = Color(0xFF1E1B4B)

    val secondary = Color(0xFF8B5CF6)
    val onSecondary = Color(0xFFFFFFFF)
    val secondaryContainer = Color(0xFFF5F3FF)
    val onSecondaryContainer = Color(0xFF4C1D95)

    val tertiary = Color(0xFFF59E0B)
    val onTertiary = Color(0xFF000000)
    val tertiaryContainer = Color(0xFFFEF3C7)
    val onTertiaryContainer = Color(0xFF78350F)

    val background = Color(0xFFF8FAFC)
    val onBackground = Color(0xFF0F172A)
    val surface = Color(0xFFFFFFFF)
    val onSurface = Color(0xFF0F172A)
    val surfaceVariant = Color(0xFFF1F5F9)
    val onSurfaceVariant = Color(0xFF475569)

    val outline = Color(0xFFCBD5E1)
    val outlineVariant = Color(0xFFE2E8F0)
    val error = Color(0xFFDC2626)
}

object MidnightPurpleDark {
    val primary = Color(0xFF818CF8)
    val onPrimary = Color(0xFF1E1B4B)
    val primaryContainer = Color(0xFF312E81)
    val onPrimaryContainer = Color(0xFFE0E7FF)

    val secondary = Color(0xFFA78BFA)
    val onSecondary = Color(0xFF1A1A1A)
    val secondaryContainer = Color(0xFF4C1D95)
    val onSecondaryContainer = Color(0xFFF5F3FF)

    val tertiary = Color(0xFFFBBF24)
    val onTertiary = Color(0xFF1A1A1A)
    val tertiaryContainer = Color(0xFF78350F)
    val onTertiaryContainer = Color(0xFFFEF3C7)

    val background = Color(0xFF0A0E27)
    val onBackground = Color(0xFFF8FAFC)
    val surface = Color(0xFF1E293B)
    val onSurface = Color(0xFFF8FAFC)
    val surfaceVariant = Color(0xFF334155)
    val onSurfaceVariant = Color(0xFFCBD5E1)

    val outline = Color(0xFF475569)
    val outlineVariant = Color(0xFF334155)
    val error = Color(0xFFF87171)
}

// ============================================
// OCEAN TEAL THEME
// ============================================
object OceanTealLight {
    val primary = Color(0xFF14B8A6)
    val onPrimary = Color(0xFFFFFFFF)
    val primaryContainer = Color(0xFFCCFBF1)
    val onPrimaryContainer = Color(0xFF134E4A)

    val secondary = Color(0xFF06B6D4)
    val onSecondary = Color(0xFFFFFFFF)
    val secondaryContainer = Color(0xFFE0F2FE)
    val onSecondaryContainer = Color(0xFF164E63)

    val tertiary = Color(0xFFFB7185)
    val onTertiary = Color(0xFFFFFFFF)
    val tertiaryContainer = Color(0xFFFFE4E6)
    val onTertiaryContainer = Color(0xFF881337)

    val background = Color(0xFFF0FDFA)
    val onBackground = Color(0xFF134E4A)
    val surface = Color(0xFFFFFFFF)
    val onSurface = Color(0xFF134E4A)
    val surfaceVariant = Color(0xFFE6FFFA)
    val onSurfaceVariant = Color(0xFF2C7A7B)

    val outline = Color(0xFFB2F5EA)
    val outlineVariant = Color(0xFFD1FAE5)
    val error = Color(0xFFDC2626)
}

object OceanTealDark {
    val primary = Color(0xFF2DD4BF)
    val onPrimary = Color(0xFF134E4A)
    val primaryContainer = Color(0xFF115E59)
    val onPrimaryContainer = Color(0xFFCCFBF1)

    val secondary = Color(0xFF22D3EE)
    val onSecondary = Color(0xFF164E63)
    val secondaryContainer = Color(0xFF0E7490)
    val onSecondaryContainer = Color(0xFFE0F2FE)

    val tertiary = Color(0xFFFDA4AF)
    val onTertiary = Color(0xFF881337)
    val tertiaryContainer = Color(0xFF9F1239)
    val onTertiaryContainer = Color(0xFFFFE4E6)

    val background = Color(0xFF0F1419)
    val onBackground = Color(0xFFF0FDFA)
    val surface = Color(0xFF1A202C)
    val onSurface = Color(0xFFF0FDFA)
    val surfaceVariant = Color(0xFF2D3748)
    val onSurfaceVariant = Color(0xFFB2F5EA)

    val outline = Color(0xFF4A5568)
    val outlineVariant = Color(0xFF2D3748)
    val error = Color(0xFFF87171)
}

// ============================================
// LEGACY COLORS (KEEP FOR BACKWARD COMPATIBILITY)
// ============================================
val primaryLight = Color(0xFF415F91)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD6E3FF)
val onPrimaryContainerLight = Color(0xFF284777)
val secondaryLight = Color(0xFF565F71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDAE2F9)
val onSecondaryContainerLight = Color(0xFF3E4759)
val tertiaryLight = Color(0xFF705575)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFAD8FD)
val onTertiaryContainerLight = Color(0xFF573E5C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val onBackgroundLight = Color(0xFF191C20)

val surfaceVariantLight = Color(0xFFE0E2EC)
val onSurfaceVariantLight = Color(0xFF44474E)
val outlineLight = Color(0xFF74777F)
val outlineVariantLight = Color(0xFFC4C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2E3036)
val inverseOnSurfaceLight = Color(0xFFF0F0F7)
val inversePrimaryLight = Color(0xFFAAC7FF)
val surfaceDimLight = Color(0xFFD9D9E0)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3FA)
val surfaceContainerLight = Color(0xFFEDEDF4)
val surfaceContainerHighLight = Color(0xFFE7E8EE)
val surfaceContainerHighestLight = Color(0xFFE2E2E9)

val primaryLightMediumContrast = Color(0xFF133665)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF506DA0)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF2E3647)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF646D80)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF452E4A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF7F6484)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF9F9FF)
val onBackgroundLightMediumContrast = Color(0xFF191C20)
val surfaceLightMediumContrast = Color(0xFFF9F9FF)
val onSurfaceLightMediumContrast = Color(0xFF0F1116)
val surfaceVariantLightMediumContrast = Color(0xFFE0E2EC)
val onSurfaceVariantLightMediumContrast = Color(0xFF33363E)
val outlineLightMediumContrast = Color(0xFF4F525A)
val outlineVariantLightMediumContrast = Color(0xFF6A6D75)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2E3036)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF0F0F7)
val inversePrimaryLightMediumContrast = Color(0xFFAAC7FF)
val surfaceDimLightMediumContrast = Color(0xFFC5C6CD)
val surfaceBrightLightMediumContrast = Color(0xFFF9F9FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF3F3FA)
val surfaceContainerLightMediumContrast = Color(0xFFE7E8EE)
val surfaceContainerHighLightMediumContrast = Color(0xFFDCDCE3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD1D1D8)

val primaryLightHighContrast = Color(0xFF032B5B)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF2A497A)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF232C3D)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF41495B)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF3A2440)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF59405E)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF9F9FF)
val onBackgroundLightHighContrast = Color(0xFF191C20)
val surfaceLightHighContrast = Color(0xFFF9F9FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE0E2EC)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF292C33)
val outlineVariantLightHighContrast = Color(0xFF464951)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2E3036)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFAAC7FF)
val surfaceDimLightHighContrast = Color(0xFFB8B8BF)
val surfaceBrightLightHighContrast = Color(0xFFF9F9FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF0F0F7)
val surfaceContainerLightHighContrast = Color(0xFFE2E2E9)
val surfaceContainerHighLightHighContrast = Color(0xFFD3D4DB)
val surfaceContainerHighestLightHighContrast = Color(0xFFC5C6CD)

val primaryDark = Color(0xFFAAC7FF)
val onPrimaryDark = Color(0xFF0A305F)
val primaryContainerDark = Color(0xFF284777)
val onPrimaryContainerDark = Color(0xFFD6E3FF)
val secondaryDark = Color(0xFFBEC6DC)
val onSecondaryDark = Color(0xFF283141)
val secondaryContainerDark = Color(0xFF3E4759)
val onSecondaryContainerDark = Color(0xFFDAE2F9)
val tertiaryDark = Color(0xFFDDBCE0)
val onTertiaryDark = Color(0xFF3F2844)
val tertiaryContainerDark = Color(0xFF573E5C)
val onTertiaryContainerDark = Color(0xFFFAD8FD)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val onBackgroundDark = Color(0xFFE2E2E9)

val surfaceVariantDark = Color(0xFF44474E)
val onSurfaceVariantDark = Color(0xFFC4C6D0)
val outlineDark = Color(0xFF8E9099)
val outlineVariantDark = Color(0xFF44474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3036)
val inversePrimaryDark = Color(0xFF415F91)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF191C20)
val surfaceContainerDark = Color(0xFF1D2024)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33353A)

val primaryDarkMediumContrast = Color(0xFFCDDDFF)
val onPrimaryDarkMediumContrast = Color(0xFF002551)
val primaryContainerDarkMediumContrast = Color(0xFF7491C7)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD4DCF2)
val onSecondaryDarkMediumContrast = Color(0xFF1D2636)
val secondaryContainerDarkMediumContrast = Color(0xFF8891A5)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFF3D2F7)
val onTertiaryDarkMediumContrast = Color(0xFF331D39)
val tertiaryContainerDarkMediumContrast = Color(0xFFA487A9)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF111318)
val onBackgroundDarkMediumContrast = Color(0xFFE2E2E9)
val surfaceDarkMediumContrast = Color(0xFF111318)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF44474E)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDADCE6)
val outlineDarkMediumContrast = Color(0xFFAFB2BB)
val outlineVariantDarkMediumContrast = Color(0xFF8E9099)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE2E2E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF282A2F)
val inversePrimaryDarkMediumContrast = Color(0xFF294878)
val surfaceDimDarkMediumContrast = Color(0xFF111318)
val surfaceBrightDarkMediumContrast = Color(0xFF43444A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF06070C)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1B1E22)
val surfaceContainerDarkMediumContrast = Color(0xFF26282D)
val surfaceContainerHighDarkMediumContrast = Color(0xFF313238)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3C3E43)

val primaryDarkHighContrast = Color(0xFFEBF0FF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFA6C3FC)
val onPrimaryContainerDarkHighContrast = Color(0xFF000B20)
val secondaryDarkHighContrast = Color(0xFFEBF0FF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFBAC3D8)
val onSecondaryContainerDarkHighContrast = Color(0xFF030B1A)
val tertiaryDarkHighContrast = Color(0xFFFFE9FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFD8B8DC)
val onTertiaryContainerDarkHighContrast = Color(0xFF16041D)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF111318)
val onBackgroundDarkHighContrast = Color(0xFFE2E2E9)
val surfaceDarkHighContrast = Color(0xFF111318)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF44474E)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFEEEFF9)
val outlineVariantDarkHighContrast = Color(0xFFC0C2CC)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE2E2E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF294878)
val surfaceDimDarkHighContrast = Color(0xFF111318)
val surfaceBrightDarkHighContrast = Color(0xFF4E5056)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1D2024)
val surfaceContainerDarkHighContrast = Color(0xFF2E3036)
val surfaceContainerHighDarkHighContrast = Color(0xFF393B41)
val surfaceContainerHighestDarkHighContrast = Color(0xFF45474C)

// Brand Accents (deprecated - use theme objects instead)
val PrimaryIndigo = Color(0xFF4F46E5)
val SecondarySlate = Color(0xFF475569)
val TertiaryGold = Color(0xFFD97706)

val backgroundLight = Color(0xFFF8FAFC)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF0F172A)

val backgroundDark = Color(0xFF0F172A)
val surfaceDark = Color(0xFF1E293B)
val onSurfaceDark = Color(0xFFF8FAFC)
